# Generated by Django 3.0.5 on 2020-04-30 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('PAR', 'Particular'), ('LAB', 'Laboral'), ('OTRO', 'Otro')], default='PAR', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('phone_type', models.CharField(choices=[('CEL', 'Celular'), ('LAB', 'Laboral'), ('PAR', 'Particular'), ('PRI', 'Principal'), ('OTRO', 'Otro')], default='CEL', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='')),
                ('created', models.DateField()),
                ('description', models.TextField()),
                ('email', models.ManyToManyField(to='contacts.Email')),
                ('phone_number', models.ManyToManyField(to='contacts.PhoneNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
