# Generated by Django 3.0.5 on 2020-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200430_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.ManyToManyField(blank=True, to='contacts.Email'),
        ),
    ]
