# Generated by Django 3.0.5 on 2020-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200501_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('FR', 'Friend'), ('FY', 'Family'), ('CO', 'Coworker'), ('OR', 'Other')], default='FY', max_length=2),
        ),
    ]
