# Generated by Django 3.0.6 on 2020-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20200506_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='contacts/static/images/default.png', upload_to='images/'),
        ),
    ]
