# Generated by Django 3.0.6 on 2020-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20200506_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='D:\\Python\\contactnow\\contact-app\\contacts/static/images/default.png', upload_to='images/'),
        ),
    ]
