# Generated by Django 3.0.6 on 2020-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20200506_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
