# Generated by Django 3.0.6 on 2020-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20200507_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('FR', 'Friend'), ('FY', 'Family'), ('CO', 'Coworker'), ('OR', 'Other')], default='Category.COWORKER', max_length=2),
        ),
    ]
